### ISSUE TITLE
How to define PlotRange

### ISSUE THREAD

**Issue by shrx** [catrasca/RadarChart#1]
is it possible to define the plot range? Ideally both axes, but the y axis range would be sufficient.

**Comment by catrasca** [comment]
shrx, plotrange is supported. Try out 

RadarChart[{{2, 2, 4, 1, 3}, {4, 3, 6, 2, 3}, {1, 2, 3, 7., 4}}, 
 ChartLegends -> None, PlotLabel -> "Left", AxesType -> "Star", 
 Filling -> Bottom, PlotRange -> {0, 10}]

**Comment by shrx** [comment]
Looks good, thanks
